export const keyCodeArr = [
  {
    keyCode: 'Backquote',
    key: '`',
    keyShift: '~',
    keyRu: 'ё',
    keyRuShift: 'Ё',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Digit1',
    key: '1',
    keyShift: '!',
    keyRu: '1',
    keyRuShift: '!',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Digit2',
    key: '2',
    keyShift: '@',
    keyRu: '2',
    keyRuShift: '"',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Digit3',
    key: '3',
    keyShift: '#',
    keyRu: '3',
    keyRuShift: '№',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Digit4',
    key: '4',
    keyShift: '$',
    keyRu: '4',
    keyRuShift: ';',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Digit5',
    key: '5',
    keyShift: '%',
    keyRu: '5',
    keyRuShift: '%',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Digit6',
    key: '6',
    keyShift: '^',
    keyRu: '6',
    keyRuShift: ':',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Digit7',
    key: '7',
    keyShift: '&',
    keyRu: '7',
    keyRuShift: '?',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Digit8',
    key: '8',
    keyShift: '*',
    keyRu: '8',
    keyRuShift: '*',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Digit9',
    key: '9',
    keyShift: '(',
    keyRu: '9',
    keyRuShift: '(',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Digit0',
    key: '0',
    keyShift: ')',
    keyRu: '0',
    keyRuShift: ')',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Minus',
    key: '-',
    keyShift: '_',
    keyRu: '-',
    keyRuShift: '_',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Equal',
    key: '=',
    keyShift: '+',
    keyRu: '=',
    keyRuShift: '+',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Backspace',
    key: 'Backspace',
    type: 'service',
  },
  {
    keyCode: 'Tab',
    key: 'Tab',
    type: 'service',
  },
  {
    keyCode: 'KeyQ',
    key: 'q',
    keyShift: 'Q',
    keyRu: 'й',
    keyRuShift: 'Й',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyW',
    key: 'w',
    keyShift: 'W',
    keyRu: 'ц',
    keyRuShift: 'Ц',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyE',
    key: 'e',
    keyShift: 'E',
    keyRu: 'у',
    keyRuShift: 'У',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyR',
    key: 'r',
    keyShift: 'R',
    keyRu: 'к',
    keyRuShift: 'К',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyT',
    key: 't',
    keyShift: 'T',
    keyRu: 'е',
    keyRuShift: 'Е',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyY',
    key: 'y',
    keyShift: 'Y',
    keyRu: 'н',
    keyRuShift: 'Н',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyU',
    key: 'u',
    keyShift: 'U',
    keyRu: 'г',
    keyRuShift: 'Г',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyI',
    key: 'i',
    keyShift: 'I',
    keyRu: 'ш',
    keyRuShift: 'Ш',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyO',
    key: 'o',
    keyShift: 'O',
    keyRu: 'щ',
    keyRuShift: 'Щ',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyP',
    key: 'p',
    keyShift: 'P',
    keyRu: 'з',
    keyRuShift: 'З',
    type: 'alphanumeric',
  },
  {
    keyCode: 'BracketLeft',
    key: '[',
    keyShift: '{',
    keyRu: 'х',
    keyRuShift: 'Х',
    type: 'alphanumeric',
  },
  {
    keyCode: 'BracketRight',
    key: ']',
    keyShift: '}',
    keyRu: 'ъ',
    keyRuShift: 'Ъ',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Backslash',
    key: '\\',
    keyShift: '|',
    keyRu: '\\',
    keyRuShift: '/',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Delete',
    key: 'Del',
    type: 'service',
  },
  {
    keyCode: 'CapsLock',
    key: 'Caps',
    type: 'service',
  },
  {
    keyCode: 'KeyA',
    key: 'a',
    keyShift: 'A',
    keyRu: 'ф',
    keyRuShift: 'Ф',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyS',
    key: 's',
    keyShift: 'S',
    keyRu: 'ы',
    keyRuShift: 'Ы',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyD',
    key: 'd',
    keyShift: 'D',
    keyRu: 'в',
    keyRuShift: 'В',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyF',
    key: 'f',
    keyShift: 'F',
    keyRu: 'а',
    keyRuShift: 'А',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyG',
    key: 'g',
    keyShift: 'G',
    keyRu: 'п',
    keyRuShift: 'П',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyH',
    key: 'h',
    keyShift: 'H',
    keyRu: 'р',
    keyRuShift: 'Р',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyJ',
    key: 'j',
    keyShift: 'J',
    keyRu: 'о',
    keyRuShift: 'О',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyK',
    key: 'k',
    keyShift: 'K',
    keyRu: 'л',
    keyRuShift: 'Л',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyL',
    key: 'l',
    keyShift: 'L',
    keyRu: 'д',
    keyRuShift: 'Д',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Semicolon',
    key: ';',
    keyShift: ':',
    keyRu: 'ж',
    keyRuShift: 'Ж',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Quote',
    key: "'",
    keyShift: '"',
    keyRu: 'э',
    keyRuShift: 'Э',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Enter',
    key: 'Enter',
    type: 'service',
  },
  {
    keyCode: 'ShiftLeft',
    key: 'Shift',
    type: 'service',
  },
  {
    keyCode: 'KeyZ',
    key: 'z',
    keyShift: 'Z',
    keyRu: 'я',
    keyRuShift: 'Я',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyX',
    key: 'x',
    keyShift: 'X',
    keyRu: 'ч',
    keyRuShift: 'Ч',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyC',
    key: 'c',
    keyShift: 'C',
    keyRu: 'с',
    keyRuShift: 'С',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyV',
    key: 'v',
    keyShift: 'V',
    keyRu: 'м',
    keyRuShift: 'М',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyB',
    key: 'b',
    keyShift: 'B',
    keyRu: 'и',
    keyRuShift: 'И',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyN',
    key: 'n',
    keyShift: 'N',
    keyRu: 'т',
    keyRuShift: 'Т',
    type: 'alphanumeric',
  },
  {
    keyCode: 'KeyM',
    key: 'm',
    keyShift: 'M',
    keyRu: 'ь',
    keyRuShift: 'Ь',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Comma',
    key: ',',
    keyShift: '<',
    keyRu: 'б',
    keyRuShift: 'Б',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Period',
    key: '.',
    keyShift: '>',
    keyRu: 'ю',
    keyRuShift: 'Ю',
    type: 'alphanumeric',
  },
  {
    keyCode: 'Slash',
    key: '/',
    keyShift: '?',
    keyRu: '.',
    keyRuShift: ',',
    type: 'alphanumeric',
  },
  {
    keyCode: 'ArrowUp',
    key: '▲',
    type: 'service',
  },
  {
    keyCode: 'ShiftRight',
    key: 'Shift',
    type: 'service',
  },
  {
    keyCode: 'ControlLeft',
    key: 'Ctrl',
    type: 'service',
  },
  {
    keyCode: 'MetaLeft',
    key: 'Win',
    type: 'service',
  },
  {
    keyCode: 'AltLeft',
    key: 'Alt',
    type: 'service',
  },
  {
    keyCode: 'Space',
    key: ' ',
    keyShift: ' ',
    keyRu: ' ',
    keyRuShift: ' ',
    type: 'alphanumeric',
  },
  {
    keyCode: 'AltRight',
    key: 'Alt',
    type: 'service',
  },
  {
    keyCode: 'ArrowLeft',
    key: '◄',
    type: 'service',
  },
  {
    keyCode: 'ArrowDown',
    key: '▼',
    type: 'service',
  },
  {
    keyCode: 'ArrowRight',
    key: '►',
    type: 'service',
  },
  {
    keyCode: 'ControlRight',
    key: 'Ctrl',
    type: 'service',
  },
];
